apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: busybox
        command: ["sh", "-c", "while true; do echo Hello Kubernetes; sleep 3600; done"]
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_CONNECTION_STRING
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
