apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: web-server
      image: nginx:latest
      ports:
        - containerPort: 8080
      # Assume this server listens on 8080

    - name: http-client
      image: curlimages/curl:latest  # A simple curl image for demonstration
      command: [ "sh", "-c", "while true; do curl http://localhost:8080; sleep 5; done" ]
      # This container will continuously make requests to the web server
