apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    disktype: ssd
#it will not schedule have to label disktype as ssd to any worker node to make it schedule or it will show pending.