apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  MYSQL_HOST: mysql
  POSTGRES_HOST: postgres
  MONGO_HOST: mongo
  MYSQL_DB: users_db
  POSTGRES_DB: users_db
  MONGO_DB: users_db
  MONGO_URI: "mongodb://mongo:27017/"
