apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
    - name: demo
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - echo "Starting pod"; sleep 5; echo "Exiting now"; exit 1;
