apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      version: stable
  template:
    metadata:
      labels:
        app: backend
        version: stable
    spec:
      containers:
        - name: backend
          image: my-backend-app:stable
          ports:
            - containerPort: 3000
