apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
  - name: stress
    image: alpine:latest
    command:
    - sh
    - -c
    - |
      apk add --no-cache stress-ng && \
      stress-ng --cpu 7 --timeout 600s
