apiVersion: v1
kind: Pod
metadata:
  name: flask-sidecar-pod
  namespace: multi-container-ns
spec:
  containers:
    - name: flask-app
      image: flask-app-image:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: shared-logs
          mountPath: /logs
      envFrom:
        - configMapRef:
            name: app-config
      livenessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 5
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"

    - name: log-sidecar
      image: sidecar-image:latest
      imagePullPolicy: Never
      volumeMounts:
        - name: shared-logs
          mountPath: /logs
      readinessProbe:
        exec:
          command: ["ls", "/logs/processed.log"]
        initialDelaySeconds: 10
        periodSeconds: 5
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "250m"

  volumes:
    - name: shared-logs
      emptyDir: {}
