# redis-replica-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-redis-replicas
spec:
  selector:
    matchLabels:
      app: my-redis
      role: replica
  serviceName: "my-redis-headless"
  replicas: 3
  template:
    metadata:
      labels:
        app: my-redis
        role: replica
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis
        command: ["redis-server", "--replicaof", "my-redis-master-0.my-redis-headless", "6379"]
---
# redis-replicas-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-redis-replicas
  labels:
    app: my-redis
    role: replica
spec:
  ports:
  - port: 6379
    targetPort: redis
  selector:
    app: my-redis
    role: replica
  type: ClusterIP
